### ISSUE TITLE
Visualisation Code

### ISSUE THREAD

**Issue by HeiMaWZ** [comojin1994/m-shallowconvnet#2]
I would like to ask to get your information on "Visualization of the temporal convolution kernels and Grad-CAM visualizations" code?

**Comment by comojin1994** [comment]
@HeiMaWZ 

Sure, what information do you need?

**Comment by HeiMaWZ** [comment]
@comojin1994 I want to visualize these two parts, but no idea how to implement them by code?

**Comment by comojin1994** [comment]
> @comojin1994 I want to visualize these two parts, but no idea how to implement them by code?

I applied for the public Grad-CAM code. It is really simple to apply the Grad-CAM algorithm to our model.

**Comment by HeiMaWZ** [comment]
> 

OK, Thank you!
