### ISSUE TITLE
True labels missing

### ISSUE THREAD

**Issue by nemesgyadam** [comojin1994/m-shallowconvnet#3]
Hi,

For data requirments i downloaded the 2a dataset from the original site.

However get_brain_data function also requires true_labels as .MAT files.
Can u please provide access to these files as well?
Where are they available?

Great repo btw, good job!

**Comment by comojin1994** [comment]
Hi,

You can download the true label at the official site of BCI Competition IV 2a.

I attached the link at below in [here](https://bbci.de/competition/iv/results/)
